### ISSUE TITLE
[Question] Preference of query string vs. BasicAuth?

### ISSUE THREAD

**Issue by stephenyeargin** [seatgeek/api-support#10]
Per the documentation:

> **Query String Parameters**
> Your can add client_id and optionally `client_secret` to the end of any valid url to authenticate your request.
> **Basic Auth**
> As an alternative to the query string, you can use HTTP Basic Auth, which is [supported] in most clients, to pass your `client_id` and optionally your `client_secret`. An example using curl can be found to the right 

_Note that "suppoorted" was corrected in the above, and probably needs to be corrected in the docs._

---
- Is there a preference to which method is used, meaning, will the other potentially be deprecated in the future?
- Any plans to add support for a custom HTTP header, e.g. `X-SEATGEEK-CLIENT-ID`, in the future?
- Is there any benefit to including the client secret if it is not required?

I've become the maintainer of the [seatgeek ruby gem](https://github.com/seatshare/seatgeek) recently, and want to ensure that anyone using it can continue to access the API and want to future-proof the code as much as possible.

**Comment by acslater00** [comment]
@stephenyeargin 

1) There are no plans to deprecate either method. Our internal api clients generally use the query string (or post data) to pass around the client id and secret, so feel free to use that for simplicity. 

2) We do not currently have any plans to support custom headers, though if there were a compelling reason to do so we could probably be talked into it

3) There is no API functionality currently available to 3rd party developers that requires the secret to be passed in the request, so there is really no benefit to doing so (or not doing so). 

Thanks, and let us know if you have any more questions

**Comment by stephenyeargin** [comment]
@acslater00 :+1:
