### ISSUE TITLE
Multiple venues for a single physical venue

### ISSUE THREAD

**Issue by lkiss80** [seatgeek/api-support#100]
This is a general platform/product question.  May I ask why there are multiple SeatGeek venues for a single physical venue?  For instance, there is only 1 Chicago Symphony Orchestra.  However, on your site, and therefore in your API, there are actually 2.  Is there a business reason behind this, or was it maybe just a mistake on the content submitted into your system?  What's interesting, is that there are events associated with each venue, so it does appear that both are actively used. 

[Chicago Symphony Center](https://seatgeek.com/venues/chicago-symphony-center/tickets) (venue id 271) 
[Chicago Symphony Hall](https://seatgeek.com/venues/chicago-symphony-hall-1/tickets) (venue id 463724)

Knowing that there is a many to one relationship from SeatGeek venue to physical venue, would be nice to know so folks can model properly in their own systems.

BTW -- Love your product :)

**Comment by chrisvoll** [comment]
Hi Larry, thanks for the report! We've merged these two venues under Chicago Symphony Center. It may take a little while for the events to reflect the change. You're correct that there should always be a 1-to-1 mapping to physical venues, so let us know if you see any other issues.

**Comment by lkiss80** [comment]
Thanks for jumping on this so quickly @chrisvoll
