### ISSUE TITLE
How to get ticket listing via api 

### ISSUE THREAD

**Issue by Nikita402** [seatgeek/api-support#101]
I am creating an app and trying to get the list of all tickets.I am able to get the list of events by client id.Is there any way to get the listing tickets via API with pricing section?

**Comment by atymic** [comment]
It's not possible to get ticket listings via their API.

> Frequently Asked Questions
Where can I get the ticket listings for an event/performer/venue?
SeatGeek has no plans to expose individual ticket listings via the API. For ticket listings you should redirect your users to the corresponding event, performer, or venue pages exposed in the url attribute of each resource.
