### ISSUE TITLE
How can we identify from the feed that the event is canceled 

### ISSUE THREAD

**Issue by mandarj08** [seatgeek/api-support#103]
Hi Team,

We need a way to identify if the event coming in the feed is canceled or not. 
I can see a field "status" coming in can that be used to solve our purpose.

Thanks!
Mandar

**Comment by aasingla** [comment]
Is there any insights into it? We are having a similar question as we are not able to figure out from the API feed if an event got cancelled. Which json field to look out for?

**Comment by vr16x** [comment]
Any update on this event cancellation ? how can we detect this via Seat Geek APIs.

**Comment by josegonzalez** [comment]
We don't include cancelled events in our API responses. You can use the absence of an event to figure out if it should no longer be available. We allow and encourage folks to make a local cache of our event catalog to do such a comparison.
