### ISSUE TITLE
Seatgeek partner tracking details

### ISSUE THREAD

**Issue by ggomezrojo** [seatgeek/api-support#11]
Hello everyone,

I had some questions after trying your Seatgeek Partner portal, please see below:
1. I assume that the 'aid' parameter mentioned in the documentation (see http://platform.seatgeek.com/#partners) is the affiliate id, or partner id as it is referred to in other places, is that correct? What's the 'rid' parameter mentioned in the documentation and how can I use it?  
2. Is there any way to get a postback call (S2S pixel) when a user I refer makes a purchase in the Seatgeek website or app?
3. In the partner dashboard, is it possible to see number of clicks? I have only been able to see # of transactions, total revenue, and a field named cost-per-click revenue. 

Thanks and best,

G

**Comment by josegonzalez** [comment]
1. For Very Large Partners™, the RID can be used to segregate tracking amongst multiple properties.
2. At the moment, this is not currently possible. I'll see about filing an issue in our internal tracker to have this implemented, but cannot make any promises around our timeframe.
3. Unfortunately, this number is not generally available at this time.

Hope this helps.
