### ISSUE TITLE
Request for Past Event Data 

### ISSUE THREAD

**Issue by JustinRush80** [seatgeek/api-support#116]
Hey,

I am an undergraduate student at Georgia Tech. For my senior project, I am trying to model event demand from 2016 to 2020 in Georgia. I was wondering if it is possible to receive a CSV with all event stats (listing_count, average_price, etc...)  that occurred in Georgia from 2016 to 2020? Also what field is the best proxy for estimating the demand of a event? 

Similar to issue (#79), I am hoping for a CSV of query: 
https://api.seatgeek.com/2/events?
datetime_utc.gte=2016-01-01
&datetime_utc.lt=2020-01-01
&venue.state=GA

Please free feel to reach out if I needed for any additional documents!

Thanks!

**Comment by sddamico** [comment]
Hey Justin sorry for the late response. Unfortunately we cannot accommodate your request at this time as we have protections around our historical data. Sorry that we can't help, good luck with your project!
