### ISSUE TITLE
Is there an API endpoint for a user's tracked performers?

### ISSUE THREAD

**Issue by vjcharles** [seatgeek/api-support#118]
I just linked my spotify account to see a few more artists and noticed the API doc has no mention of 'tracked' artists or seeing specific user info. 

I was just getting a users' tracked artists from spotify's API directly but mapping those to seatgeek wasn't 1-to-1. The method used was this call which returns a list of too many different results: 

    https://api.seatgeek.com/2/performers?q=arcade+fire

Please direct me to a more appropriate place for this question too if there is a better forum for this feature-request meets API question. 
Thanks!

**Comment by sddamico** [comment]
Unfortunately this API is not part of our public API at this time, sorry.
