### ISSUE TITLE
call url pagination - what is maximum `per_page` value ?

### ISSUE THREAD

**Issue by gigmaps** [seatgeek/api-support#12]
trying to get a data dump of all events using the `per_page` value in the call url
however the documentation doesn't give an idea of maximum for this value ?

what's the maximum value we can use for `per_page` ?
what do you prefer ?  lower `per_page` value higher call frequency ? ...or less calls with higher `per_page` value ?

eg in a previous discussion a value of `2000` was used as an example, but not defined as a limit:
https://zohodiscussions.com/sgplatform/topic/data-dump-of-events

**Comment by gigmaps** [comment]
i notice that with a `per_page=10000` we get the following response:
`{"status":400,"message":"page size too large. maximum 5000","meta":{"status":400}}`

would be good if you could include this in the documentation and tell us if it's ever updated.  thanks.

**Comment by bfinamore** [comment]
Sorry, moved my question to a new issue.
