### ISSUE TITLE
Quick question on Seatgeek listings

### ISSUE THREAD

**Issue by mlopalo** [seatgeek/api-support#121]
Hi! I'm looking into using the Seatgeek API and just had a quick question I couldn't find the answer to in the documentation. Do the listings that are pulled through the API include only listings that originated on Seatgeek (so, listings where the seller uploaded the ticket directly to Seatgeek)? Or do they include listings from other websites such as StubHub that Seatgeek aggregates?

**Comment by dallasgutauckis** [comment]
Assuming you're referring to this from events, 

![image](https://user-images.githubusercontent.com/117083/168650725-b901ce36-192d-419d-9b7b-81c5bdc25287.png)

then this is representative of stats for listings only available on SeatGeek (albeit how they were added is not limited to direct listings from resale). We do not have or include stats from other sites/platforms.

**Comment by mlopalo** [comment]
Hi Dallas,

Thanks so much for the quick response - this is helpful. Can you clarify
what you mean by "albeit how they were added is not limited to direct
listings from resale?"

I know Seatgeek aggregates listings from other websites - is the correct
understanding that the Seatgeek website/app shows listings pulled from
other websites, but the API draws a subset of those listings that
originated and were uniquely listed on SeatGeek?

Thanks again!
