### ISSUE TITLE
artist events (past & upcoming)

### ISSUE THREAD

**Issue by TheFranciscoMartinez** [seatgeek/api-support#122]
Current the list of events is limited to 10 per search.
Im looking to access to a given artist complete events history upon search. Is this something that can be done? 

thank you

**Comment by dallasgutauckis** [comment]
We don't have event history as part of the API. SeatGeek is not & does not purport to be a canonical/definitive source of event information. 

The API supports pagination, as documented under the "Pagination" heading on https://platform.seatgeek.com, screenshot for reference:

<img width="989" alt="image" src="https://user-images.githubusercontent.com/117083/172020679-70c3c635-ecad-4ec8-9ed0-dd026363303b.png">
