### ISSUE TITLE
Error: Request failed with status code 403

### ISSUE THREAD

**Issue by danieldanielecki** [seatgeek/api-support#123]
Can someone help me why I've been getting 403 since a few months back on my social[at]tamotam.com account?
The support "reachable" via hi@seatgeek.com is useless, as it never replies, other than automatic replies.

**Comment by theFoxxxxxx** [comment]
Hi, trying using seatgeek's cURL command in their API documentation. This worked for me when I got a 403.

**Comment by danieldanielecki** [comment]
Before `per_page` I've had `?` (like the docs...) instead of `&`...
