### ISSUE TITLE
Image Resolution

### ISSUE THREAD

**Issue by cpvertex** [seatgeek/api-support#13]
When I pull images down from the API they appear to be very low resolution (280x210). Is there any way to get higher resolution images? 

In case you need it for this question, here is how I am connecting and retrieving the image. Client ID left out intentionally for post but I get the same results with it included.
https://api.seatgeek.com/2/events?lat=30.25&lon=-97.75&range=50mi&per_page=1

From the returned JSON I am looking at Event ID 3108267. The image url returned for this is:
"image":"https:\/\/chairnerd.global.ssl.fastly.net\/images\/performers-landscape\/robert-earl-keen-3e0c82\/1546\/huge.jpg"

The same low resolution image is returned under performers if I request the event directly through:
https://api.seatgeek.com/2/events/3108267

Thank You

**Comment by josegonzalez** [comment]
We don't currently provide higher resolution images to external api users, and as far as I know, we have no immediate plans to do so.

The `huge` name is a bit of a legacy thing where they were _actually_ huge images in comparison to where we used them ~5 years ago :)

**Comment by surfboarddude** [comment]
Hi I wanted to ask if Seat geeks solved the low quality image!
