### ISSUE TITLE
Not able to access api from another country

### ISSUE THREAD

**Issue by ankit-greateventever** [seatgeek/api-support#14]
Hi seatgeek team,
I am ankit gupta one of the founder of great event ever website , we have joined your partner program we are trying to develop our application to display your events. by accessing your api but not getting response from api.
https://api.seatgeek.com/2/events This is giving response website can't be reached. 
I guess the issue is because we are trying to access it from outside US , we are trying to access it from INDIA. because if we change the virtual location of browser api gives us response but we can not develop application from deveoper tool (eclipse) using virtual location. 
Could you please suggest us any way to access your api from our country.

Thanks,
Ankit
Mobile No. +918376024944
email-id - ankit.gupta@greateverevent.com

**Comment by austinov** [comment]
Hi team,

we seem to have the same issue. Our service uses seatgeek API for searching events.
Lately we have timeouts (dial tcp 54.227.238.103:443: i/o timeout) on getting response for https://api.seatgeek.com/2/venues?country=france (and other countries - us, uk...).
The service is hosted in Russia (on 109.234.37.213).

Thanks for your help.

**Comment by josegonzalez** [comment]
Unfortunately, SeatGeek appears to be inaccessible from your location. Apologies.

**Comment by austinov** [comment]
Let me ask, inaccessible of the SeatGeek service for Russia users is a temporary or strategic decision of the company?

**Comment by pandeiro** [comment]
Wonder how much money SeatGeek is leaving on the table because they can't figure out internationalization. /cc @techcrunch
