### ISSUE TITLE
[enhancement] ISNI support for artists

### ISSUE THREAD

**Issue by slaght** [seatgeek/api-support#15]
Hi again,
Recently, The Echo Nest announced the [shutdown of their API](http://developer.echonest.com/docs/v4/) and requesting all users migrate to Spotify.  However, they are not migrating all of their useful features to the Spotify API.  In particular, they are seemingly dropping support for Project Rosetta Stone, which you guys have had built in to your API.  

Now, since the application I am building translates IDs across different services (MusicBrainz->SeatGeek), I am currently in a pickle with this API shutdown.  Would you ever internally consider implementing another function like this, such as the ISNI database?

Cheers,

**Comment by slaght** [comment]
Update on this: it would also suffice to have more narrow query functionality, such as limiting artist query scope to just the artist names, or limiting event query scope to the performer name

**Comment by josegonzalez** [comment]
Woops, didn't notice this issue!

@BrandonSlaght What would the ideal api url look like for your narrow query functionality?

**Comment by slaght** [comment]
@josegonzalez Maybe something like
`https://api.seatgeek.com/2/performers?q=red+hot&scope=name` (or events, or venues, ect)
Where if scope is included, the query is treated as it currently is, searching through everything.  However, I have never designed an API before so I have no clue if this violates your design or RESTful principles.

**Comment by josegonzalez** [comment]
I don't understand what the scope does in your query.

**Comment by RockinVideo** [comment]
Regarding ISNI number (15), come again??

**Comment by RockinVideo** [comment]
Let me understand this, I asked for SeatGeek's help weeks ago, Really, you guy's don't even answer you're phone.  BTW, I really don't care who you're affiliated with.

Respectfully,

Mr. Michael J. De Grado

**Comment by RockinVideo** [comment]
We're not doing anything wrong. Ask for support all you want.  [crowdattendance & musiccurtain are just trying to increase sales.]. Sorry 

Respectfully,

Mr. Michael J. De Grado

**Comment by RockinVideo** [comment]
Number (#16) is more than (#15), but how many more then (20):)...

**Comment by slaght** [comment]
Scope would, for example, narrow the query to only searching for names matching the query, as opposed to searching in the name, event, and venue fields.

**Comment by josegonzalez** [comment]
Oh I see.

I don't think we can go down this route as it'll change the semantics of our search api (for both internal and external clients). Using the `q` argument to search performers is enough (it should bring up RHCP for that query you show) and then you can filter the events endpoint by that performer id.

I'll bring up internally the ISNI issue, but I don't think we'll implement a solution for this anytime soon.
