### ISSUE TITLE
Ticket scanning

### ISSUE THREAD

**Issue by hkaya1** [seatgeek/api-support#157]
We are developing a Linux-based camera app for guests to scan their mobile-only tickets and find directions to their seats.
Is there a method for decrypting the scanned mobile QR or barcode ticket using SeatGeek API?

**Comment by sddamico** [comment]
Can you elaborate on what you mean by "decrypting"?

**Comment by hkaya1** [comment]
When we scan the mobile barcode ticket, we get some ticket information like this:

`BAEAf2a+9CJnTRobAAAAAQAAAACcXOeFIxGamZAZHJ//C2sAYlrmVFvlFijyujwI::705929::926259::1690394010` 
or
`BAEAf2a+9CJnTRobAAAAAQAAAACcXOeFIxGamZAZHJ//C2sAYlrmVFvlFijyujwI::566601::104745::1690393995`

We would like to extract (or decrypt) the following type of seat information from this scanned ticket data:

`{ "venue" : "Petco Park", "section" : 324, "row" : 27, "seat" : 23 }`

This is the sample ticket which returned the above data upon scanning:
![image](https://github.com/seatgeek/api-support/assets/53856479/aac9508a-cfdc-4dc9-bd4b-23a16b00cd8b)

**Comment by sddamico** [comment]
The ticket in your screenshot is a Ticketmaster ticket. I'm afraid SeatGeek can't offer much help here.

**Comment by sddamico** [comment]
Speaking generally about our industry, it is highly improbable that venue or section/row/seat information would be encoded in a barcode like that as the information density would affect scanning. For a ticketing company, we can look up a ticket by barcode in our server and get that associated metadata so it doesn't need to be encoded.

**Comment by hkaya1** [comment]
Will the same venue have the options to purchase tickets through SeatGeek or Ticketmaster? My understanding was that even if a ticket was bought through SeatGeek, one would have to access the ticket through Ticketmaster on the MLB Ballpark app.

Thank you for the additional insight. My question would be that if we are to scan such a barcode, would the barcode data be used in the payload body of the API request as is? Which endpoint would this be for SeatGeek, as I can not see such information on the public documentation (https://platform.seatgeek.com/)? We would like to become a partner to access this API if possible.

My understood operational flow is as follows:
Scan ticket using camera → POST scanned ticket data to SeatGeek endpoint → Receive response including seat information

**Comment by sddamico** [comment]
We do not have a public API for looking up ticket information by barcode, sorry.
