### ISSUE TITLE
OR query to look up events by venue id not working as intended?

### ISSUE THREAD

**Issue by bjahnke** [seatgeek/api-support#158]
My app searches events by venue id. I try to put as many venue ids in a single request as possible. Recently, I've notice that the number of events returned by this approach has been significantly reduced (50 events returned for 194 venue ids). Sending 1 venue id per request yields over 5000 events total. Sending 2 venue ids per request yields only about 4000 events total. 

Is this a bug? Or should I be using 1 venue id per request if I want stable results?

**Comment by johnthedebs** [comment]
The results are paginated, and we recently reduced the page size to 50. If you want all events for the venues being queried, you will have to request subsequent pages.

**Comment by bjahnke** [comment]
Ah of course. Overlooked that, thanks!
