### ISSUE TITLE
Pagination Duplicates / Best Practices

### ISSUE THREAD

**Issue by bfinamore** [seatgeek/api-support#16]
Hi,

I'm doing a search for venues in Pittsburgh and I see that out of 894 results, about 29 venues are duplicated when I paginate 100 at a time and increment page on subsequent calls.  I'm wondering if this is a side effect of the API with the pagination method that I'm using, or if there is something weird going on with my xml parser or something.  

Any thoughts on how to ensure that paginated results are unique and complete would be much appreciated.

Thanks,
Brian 

https://api.seatgeek.com/2/venues/?format=xml&lat=40.440624&lon=-79.995888&range=25mi&per_page=100&page=1

**Comment by josegonzalez** [comment]
Because of how the lat/lon parameters are implemented, you will see venues drift in and out of page. As an alternative, you could use the `city` parameter and then add a sort field. The sort field might also work for lat/lon.
