### ISSUE TITLE
musiccurtain.com

### ISSUE THREAD

**Issue by RockinVideo** [seatgeek/api-support#17]
Hi!  I'm trying to add my client id & my client secret?  On my website do I Use hppts://api.seatgeek.com/2/events/client id = my client id that was provided to me by seat geek & my client secret that was also provided.  Or do I use my own https://api.musiccurtain.com/2/events/client id?  Hmm....

**Comment by dallasgutauckis** [comment]
Use the client ID provided by SeatGeek.
