### ISSUE TITLE
Support for international "venue.state"

### ISSUE THREAD

**Issue by adrianscott83** [seatgeek/api-support#18]
I'm currently integrating SeatGeek into my site with a lot of success except for the handling of international states.  I have a generic list of events occurring at different places all over the world and provide a method to perform searches on specific locations based on the city, state, or country name using values returned by the API.

It seems that when I provide anything other than a US or Canadian state name, I get a `SeatGeekConnector::ResponseError` error.

In this case I am testing with: `city=Manchester&state=Lancashire&country=UK` which fails on Lancashire, even though this is the same state returned by the API.  Is there a way to get around this issue?

**Comment by josegonzalez** [comment]
In many cases, we don't have the correct state attribute for international events - or a state is really a province, etc. It'll be a bit of engineering work to get this correct for all of our international venues, but I'll file an issue and hopefully we can rectify this.

For now, I'd stick with using `venue.city` and `venue.country` for international events.
