### ISSUE TITLE
Event End Times

### ISSUE THREAD

**Issue by acharyaamrit** [seatgeek/api-support#19]
Hi, Love your API! thank you. 

I have a question on event ending times. I notice you dont have this information in the API. Is there any way this can be derived? Is the "visible_until_utc" somehow related to the event ending time? Or is there another way to find a specific time an event ends. 

Thank you.

**Comment by josegonzalez** [comment]
If I'm not mistaken, the `visible_until_utc` time is when we turn off showing listings for an event, which may or may not coincide with the event ending. 

As many performances do not necessarily have a set end time - ever been to a 19 inning Red Sox/Yankees game? - in many cases do not have access to this information and therefore do not expose it.
