### ISSUE TITLE
[Documentation] Incorrectly states that non-SSL connections allowed

### ISSUE THREAD

**Issue by stephenyeargin** [seatgeek/api-support#2]
When viewing [the documentation](http://platform.seatgeek.com/), all of the links to API resources are written as `http://api.seatgeek.com/2/<method>`. However, as of a recent change, all of these are being redirect to their http**s** counterparts. 

```
$ curl -I http://api.seatgeek.com/2
```
```
HTTP/1.1 301 Moved Permanently
Server: openresty
Date: Tue, 09 Feb 2016 03:54:02 GMT
Content-Type: text/html
Content-Length: 178
Connection: keep-alive
Location: https://api.seatgeek.com/2
X-Served-By: lb-14-04-i-8152c308
```

The implication here is that certain code, such as [a SeatGeek gem](https://github.com/dmvt/seatgeek), does not properly handle the redirect.

**Related:** https://github.com/dmvt/seatgeek/issues/4

## How to resolve:

- [ ] Update documentation -or-
- [ ] Stop forwarding requests to SSL

**Comment by josegonzalez** [comment]
Good catch! We made this change a few weeks ago. I'll update the documentation.

**Comment by josegonzalez** [comment]
@stephenyeargin The new docs should be out soon. I totally neglected the Google Groups, and will make an announcement about this there.

Again, thanks for the heads up!
