### ISSUE TITLE
Is there a way to query past events

### ISSUE THREAD

**Issue by gcaseycupp** [seatgeek/api-support#20]
I seem to always get no data for past events in the past.

**Comment by josegonzalez** [comment]
Sorry I must have missed this.

At this time, our api does not expose past events. You are free to archive our resultset for future usage though.

**Comment by agaur79** [comment]
not been able to find out the venue map api..
so that i may able to implement seat mapping in my application using seetgeek developers api

**Comment by zackkitzmiller** [comment]
At this time, we don't publically expose our mapping APIs.
