### ISSUE TITLE
can not use partner code

### ISSUE THREAD

**Issue by russfustino** [seatgeek/api-support#21]
When I use this, I get data...
https://api.seatgeek.com/2/events?performers.slug=ani-difranco

when I append my partner code as a parameter I do not get data:

https://api.seatgeek.com/2/events?performers.slug=ani-difranco?aid=PARTNERAID

I have registered the app and have a client ID and secret, but when I use those as parameters I get invalid authentication. not sure if that is related. Please advise. email russ@fustinbrothers.com

**Comment by josegonzalez** [comment]
As you already had a question mark in the url, you'll need to use an ampersand - `&` - instead of a question mark to separate the query parameters. Here is an example:

```
https://api.seatgeek.com/2/events?performers.slug=ani-difranco&aid=PARTNERAID
```

**Comment by russfustino** [comment]
Duh! Thanks. That's what I get for working on the app at happy hour on Friday!
