### ISSUE TITLE
Events without Tickets?

### ISSUE THREAD

**Issue by pjameson** [seatgeek/api-support#22]
Hi,

This is a question not an issue. I'm receiving events from the API and when I click on the URL, there are actually no tickets available for the event on the seatgeek platform. Here are a few examples:

https://seatgeek.com/valley-queen-tickets
https://seatgeek.com/surf-curse-tickets

Is there some attribute in the API response that tells me whether there are tickets available or not? I don't want to show events unless tickets are available to be purchased.

Thanks!

Pete

**Comment by josegonzalez** [comment]
Each event object has a `stats.listing_count` property which contains a recent - ad of when we last saw the event - count of listings available. We also show some aggregate pricing information in the `stats` property which may be useful.
