### ISSUE TITLE
Limit num events per day / taxonomy?

### ISSUE THREAD

**Issue by pjameson** [seatgeek/api-support#23]
Hi,

This is not an issue, but a question / enhancement request. Is there a way to limit the number of events returned for a given day? Like say, give me 10 events per day for the next 60 days. How about number of events per day by taxonomy? Give me 3 Sports events, 5 Concert events and 3 Theatre events per day for the next 60 days.

Do I need to request a bunch of events and perform that filtering on my end?

Thanks,

Pete

**Comment by josegonzalez** [comment]
There isn't such a thing in our API. For our own internal autocomplete endpoints, we perform such filtering - on a type level at least - manually, which is the best recommendation I have.

I would probably ingest our API once a day - when you do that is up to you - and have a an API service layer on top of your data store which can perform such aggregations for you. That should give you the flexibility to do whatever response types you want for your use case.
