### ISSUE TITLE
Date query not working in my ajax call

### ISSUE THREAD

**Issue by jcincotta22** [seatgeek/api-support#25]
When I run the query in the browser for an artist name, start date, and end date it works fine...when I run it on my application It returns all results starting from todays date...why is this happening??

**Comment by josegonzalez** [comment]
Without knowing any details of your application code, I'll say you're probably setting an invalid date - maybe date formatting is wrong - in your code, so it's actually not passing any dates. Happy to help debug that issue if you can show us the code you are using.

**Comment by josegonzalez** [comment]
Closing as there hasn't been any response in two weeks. Hope you figured out your issue :)
