### ISSUE TITLE
API Rock & Hard Rock categories contain non-rock artists, need help...

### ISSUE THREAD

**Issue by ruaridhcurrie** [seatgeek/api-support#26]
Hi,

My name is Ruaridh Currie. I am founder of Rockifi.com. We are launching our beta version of Rockifi in 2 weeks time. Rockifi is a social website aimed at fans of rock music, heavy metal and alternative music.

We have implemented the Seatgeek API successfully, however there is a major issue. Categories we want to show such as 'Hard Rock' and 'Rock' returns items like Katy Perry, Pink & even Barbara Striesand!! - obviously these are not hard rock artists!

Is there anyway to remove these from the Rock and Hard Rock categories without having to do it manually every time an artist appears in the wrong category with your API?  - I noticed even on your website these artists are not in the correct category: https://seatgeek.com/concert-tickets/hard-rock (see Katy Perry in there)

Thanks and look forward to your response.

**Comment by josegonzalez** [comment]
Interesting. I'll try and take a look at this something this week, but iirc we retrieve this information from musicbrainz, so it might not be super easy to clean this up. Thanks for the heads up.

**Comment by josegonzalez** [comment]
Closing as we, internally, are working on a project to improve our genre information. Thanks for reporting this!
