### ISSUE TITLE
seatgeek API Vs seatgeek website's event list 

### ISSUE THREAD

**Issue by shihabvk** [seatgeek/api-support#28]
We have searched for event name "Los Angeles rams at" in seatgeek API and we only able to find 2 events, but in https://seatgeek.com/ website we found more than 2 events.

**Comment by chrisvoll** [comment]
@shihabvk Am I correct that you're looking to search for events by the away team? If so, you can find all of the away games for the Los Angeles Rams using a query that looks like this, which is better than searching using the event name:

> https://api.seatgeek.com/2/events?performers[away_team].slug=los-angeles-rams

As of my writing this, there are three scheduled away games. More documentation is available on [our platform page](http://platform.seatgeek.com/#events). Let me know if this helps!

**Comment by shihabvk** [comment]
@chrisvoll Thanks for your Quick response.
From your link https://api.seatgeek.com/2/events?performers[away_team].slug=los-angeles-rams it returns 3 events but in the seatgeek website search box , I used same word "los-angeles-rams" and it returns 6 results?

**Comment by josegonzalez** [comment]
@shihabvk You're looking for away games, and our site shows both away *and* home games. That is why our site shows 6 events instead of 3.

**Comment by shihabvk** [comment]
@josegonzalez Thanks for your reply.
So how i get both away and host events through API? Which parameters I need to send?

**Comment by josegonzalez** [comment]
You'll want `performers.slug`: https://api.seatgeek.com/2/events?performers.slug=los-angeles-rams
