### ISSUE TITLE
Higher "per page"

### ISSUE THREAD

**Issue by elrazia** [seatgeek/api-support#29]
Hi,

I am trying to retrieve upcoming schedules for Big 4 sports teams. I used the call:

```
curl https://api.seatgeek.com/2/events?performers.slug=new-york-mets -u MYCLIENTID:MYCLIENTSECRET
```

to obtain upcoming events for the NY Mets. The metadata reads:
```
"meta":{"per_page":10,"total":192,"page":1
```

My question is, what parameters would I pass and where would I pass them to alter those numbers. I'd either like to have all of the results on 1 page, or be able to iterate through the pages grabbing the results.

Thanks in advance!

**Comment by josegonzalez** [comment]
You can set a `per_page` value of anything up to 1000, as specified in our [platform documentation](http://platform.seatgeek.com/).
