### ISSUE TITLE
Excluding Taxonomies from Events Query

### ISSUE THREAD

**Issue by laurengibbonz** [seatgeek/api-support#3]
Hi,

I'm not having an issue with the API but saw this forum was where I could post questions. 

Is there a way to exclude/filter taxonomies (by ID or name) from an events query? For example, I would like to get all events except those in the sports taxonomy? I see you have filter options for events by pricing parameters. 

If there is no way to exclude a taxonomy do you recommend I build the API with all the taxonomies I do want, e.g. https://api.seatgeek.com/2/events?taxonomies.name=sports&taxonomies.name=concert   ?

Thank you,
Lauren

**Comment by garetht** [comment]
Hi,

Unfortunately, we do not have a way to exclude particular taxonomies from a search query, only specify the ones that you wish included. Listing only the taxonomies you want, as you suggest, would be an excellent way of working around this. Thanks for using our API!

SeatGeek

**Comment by josegonzalez** [comment]
@laurengibbonz What would the syntax for exclusions look like? As far as I know, we don't have anything similar to that. The only potentially applicable filters are range filters, which *could* work for taxonomy IDs, but certainly not for names.
