### ISSUE TITLE
events taxonomies argument not filtering

### ISSUE THREAD

**Issue by gigmaps** [seatgeek/api-support#30]
If i run the following API call I get ~45k events :
`https://api.seatgeek.com/2/events?format=json&aid=10489&taxonomies.name=concert&client_id=xxxxx`

However the event `type` is not always `concert` - in fact the results are _**highly**_ polluted with other event types - the following being a list of count(*) by event type :
```
auto_racing						57
basketball						164
boxing							30
broadway_tickets_national				5735
cirque_du_soleil					637
classical						712
classical_opera						536
classical_orchestral_instrumental			959
classical_vocal						34
comedy							4863
concert							26534
dance_performance_tour					2176
european_soccer						169
extreme_sports						5
family							2110
fighting						3
football						20
golf							8
hockey							923
horse_racing						1
international_soccer					12
literary						17
minor_league_hockey					1022
mlb							326
mls							19
mma							52
monster_truck						164
motocross						38
music_festival						711
nascar							13
nascar_nationwide					3
nascar_sprintcup					14
nba							560
nba_dleague						106
ncaa_baseball						504
ncaa_basketball						4084
ncaa_football						10
ncaa_hockey						518
ncaa_womens_basketball					3750
nfl							9
nhl							537
olympic_sports						25
pga							52
rodeo							191
soccer							176
sports							451
tennis							87
theater							5277
wrestling						38
wwe							144
```

...it would in fact appear that the `taxonomies.name` argument doesn't work at all ?

Is there any way to ensure that results are ONLY returned for my selected 'concert' taxonomy ?

**Comment by josegonzalez** [comment]
I just did the following to try and replicate your results:

```
https://api.seatgeek.com/2/events?taxonomies.name=concert&client_id=CLIENT_ID&type=ncaa_womens_basketball
```

And am unable to. Can you point out to me an event where the event type doesn't closely match the taxonomy? They get derived from each other internally, so it would be very strange to actually see this happen so... frequently.

Sorry for the late response.

**Comment by gigmaps** [comment]
@josegonzalez thanks for the reply - it looks like you've fixed it somewhat since I asked the question originally (and I developed my own code to filter out the undesired types anyway)
btw you don't actually have any `ncaa_womens_baskeball` events listed on the API currently :-)

**Comment by josegonzalez** [comment]
I don't follow College Sports as well as I should, but didn't Women's Basketball just finish their season? We don't have a schedule yet for next year - not sure anyone does - so that's why we wouldn't list any events for them :)

**Comment by josegonzalez** [comment]
Closing the issue as this appears to have been ephemeral.
