### ISSUE TITLE
Countries missing in API?

### ISSUE THREAD

**Issue by rutgerg** [seatgeek/api-support#34]
Hello,
https://api.seatgeek.com/2/events?client_id={API_KEY}&venue.country=US&per_page=25&page=1 works well for me but
https://api.seatgeek.com/2/events?client_id={API_KEY}&venue.country=DE&per_page=25&page=1 for Germany returns no results. I tried ES for Spain and NL for Netherlands as well. These countries do have event according to the website.

Can you help me?

**Comment by josegonzalez** [comment]
Do you have an example where we have events in Germany or elsewhere?

**Comment by rutgerg** [comment]
https://seatgeek.com/hamburger-sv-at-fc-bayern-munich-tickets/european-soccer/2017-02-25-3-30-am/3439822

**Comment by josegonzalez** [comment]
Looks like you will need to type out the entire country name, such as `Germany`. I'll open a ticket internally regarding supporting all country codes, but for now that is the work around.

Thanks for reporting this :)
