### ISSUE TITLE
Looking to Create a Seatgeek Sidebar

### ISSUE THREAD

**Issue by JohnMikulec** [seatgeek/api-support#35]
We want a Seatgeek Section on our Individual Sidebars for Each City on our site. So we want a sidebar sized ticket window that shows all major upcoming sporting events and stadium concerts.

**Comment by josegonzalez** [comment]
Is there a specific question you are asking here? Our [platform docs](http://platform.seatgeek.com/) show how to pull events down from our api.

**Comment by JohnMikulec** [comment]
How do we get the list of events or venues or city api codes? It only shows an example but not how to find the specific inputs for Say Bank of America Stadium in Charlotte.

**Comment by JohnMikulec** [comment]
Is there a list of Venue Ids

**Comment by josegonzalez** [comment]
Generally, you just query the individual endpoints - `/events`, `/venues` - for that. You can use the `q` to search with a "wildcard". Example for your search:

```
https://api.seatgeek.com/2/venues?client_id=YOUR_CLIENT_ID&q=Bank%20of%20America&city=Charlotte&per_page=1
```

Our endpoints support pagination using the `page` and `per_page` querystring arguments, so you can use that to iterate over all of our event/performer/venue information.

You can also pull down our entire api, store it in a database, and filter it on your end. We recommend doing so once a day to ensure you have the freshest information.

Hope that helps.

**Comment by JohnMikulec** [comment]
How do we insert that search into the html?

**Comment by josegonzalez** [comment]
SeatGeek doesn't provide any such widget to partners, and you'll need to have your development team turn those results into html that you can use on your website.

**Comment by JohnMikulec** [comment]
Are there any widgets out there that would work? I thought this would be a lot more user friendly to link in with you guys.

**Comment by josegonzalez** [comment]
Most integrations are custom to your specific platform/website - and aren't necessarily on the client side, or in the same language - and thus we don't offer anything official.

Our platform is designed such that external partners can customize exactly how they integrate without us dictating much of their design.

**Comment by JohnMikulec** [comment]
Are there ways to do just banner ads that we get our cut on until we can get this developed?
