### ISSUE TITLE
Team logos

### ISSUE THREAD

**Issue by holman** [seatgeek/api-support#36]
Do you happen to have any plans on maybe adding a `logo` attribute to a performer (or to the `images` array) in the future?

Looking through SeatGeek, it seems like most leagues just show the stadium for individual team images, which is understandable. But for the MLS you have reallllll dope logos [shown for each team](https://seatgeek.com/mls-partnership).

The format of the URL for the logo includes `mls-partnership`:
https://chairnerd.global.ssl.fastly.net/images/new/mls-partnership/teams_logos/@2x/san-jose-earthquakes.png

...so I'm kinda guessing the answer might be "nope, sorry!", unless you have permissive terms with the MLS. But I figured I'd ask just in case. :) Would be really sharp to be able to list out at least the MLS for now (and any other team logos in the future) in our applications, and I'd otherwise avoid hotlinking the images unless that was specifically cool with y'all.

Cheers! Really love the API; kudos to the whole team. So many APIs are a huge pain to work with, but SeatGeek's has been lovely so far.

**Comment by josegonzalez** [comment]
Any logos we display on our site are not available via API, and therefore you will wish to seek a specific license with the respective property holders.

At this time, the only logos or images we allow our API users to embed are those which are currently exposed via the API. Please also note that these images are subject to change at any time, pending changes in licensing, image availability, etc.

So I guess the answer is "nope, sorry!" (they are hella dope though).

**Comment by josegonzalez** [comment]
Also, I would refer to the licensing for the specific organizations in question. In this case, I believe the correct location for the MLS is [here](https://www.mlssoccer.com/terms-service).

**Comment by holman** [comment]
Makes sense. Thanks!
