### ISSUE TITLE
payment question

### ISSUE THREAD

**Issue by ShaharKeret12** [seatgeek/api-support#38]
i didnt quite understand if there is a payment for using SeatGeek's API, it is free for use? monthly payment?other?
thanks for the help

**Comment by gabalicious** [comment]
It's free to use. Just register for an api_key and try it out. 
https://api.seatgeek.com/2/events/3593247?client_id=api_key

You can refer to their documentation for how to use their api. 
http://platform.seatgeek.com

**Comment by josegonzalez** [comment]
What @gabalicious said. Our API - as documented on our platform site - is free for public consumption.
