### ISSUE TITLE
[Question] Sort events by location proximity to geoip

### ISSUE THREAD

**Issue by BrandonSlaght** [seatgeek/api-support#4]
Is this possible?  I know you can use the geoip=true query to get local events, but it would be very useful to me to say, get a list of concerts for an artist that are sorted by closeness to the requester's ip address.

**Comment by josegonzalez** [comment]
@zackkitzmiller I don't believe this is possible at the moment, is that correct?

**Comment by zackkitzmiller** [comment]
That's correct, there is currently no way to sort by geolocation. I'll look into the feasibility of adding it.

**Comment by BrandonSlaght** [comment]
Awesome, thank you!

**Comment by josegonzalez** [comment]
@zackkitzmiller Did you ever take a look at this?

**Comment by josegonzalez** [comment]
Closing. The issue was filed internally, and though I cannot provide any eta, I'll be sure to bump this issue if/when it's done.
