### ISSUE TITLE
Seatgeek in Australia

### ISSUE THREAD

**Issue by pi-ron** [seatgeek/api-support#40]
Hello,

We have several clients who use SRO for their venue ticketing. We are currently looking into building a custom app using the SRO API for one of our clients to improve the user experience in purchasing their tickets.

I've had a bit of a look through Seatgeek's Platform pages but I'm a bit unsure how it would work with an Australian venue.

Are there any Australian venues on Seatgeek?

Can the Seatgeek Platform be used to build a custom web app to integrate with the SRO API?

**Comment by erwaller** [comment]
@pi-ron we're not quite ready to provide SRO API (which is currently distinct from the SeatGeek Platform API) support on github yet. Could you email elir@toptix.com with what you're trying to accomplish?

**Comment by pi-ron** [comment]
@erwaller thanks for getting back to me.  

Do you have any roadmap for Australian venues being able to use Seatgeek?
