### ISSUE TITLE
My company (sidekix app) registered to seatgeek partner program, I have some questions

### ISSUE THREAD

**Issue by yehoshuas** [seatgeek/api-support#41]
a) how can we know using the API if tickets are available for an event?
for eaxmple I get a 'No tickets available' error when calling this url
https://seatgeek.com/rob-riggle-tickets/comedy/2019-01-01-9-pm/2687179 
b) in 'https://seatgeek.com/tba/articles/seatgeek-partner-program-instructions-info/' you gave an example of how to set an affiliate link what does rid mean?
https://seatgeek.com/new-york-knicks-tickets?aid=xxx&rid=yy

**Comment by josegonzalez** [comment]
- You can generally check `stats.listing_count` to see if there are listings for an event. This is not guaranteed to be up to date in all cases, but should be fairly accurate. We use the `stats` object for representing generic pricing information on our performer pages.
- The `rid` can be considered a subcategory for affiliates. Generally this is used only for large publishers that wish to track multiple sub-properties in a single account.

**Comment by yehoshuas** [comment]
thanks, I have another question.

how can it be that there are events with listing_count > 0, but date_tbd = true

for example:
calling this URL: 
https://api.seatgeek.com/2/events/3693387?client_id=

returns a JSON response with listing_count = 1473, date_tbd = true & time_tdb = true

{"url":"https:\/\/seatgeek.com\/eastern-conf-semifinals-tbd-at-cleveland-cavaliers-home-game-1-date-tba-tickets\/5-1-2017-cleveland-ohio-quicken-loans-arena\/nba\/3693387","datetime_local":"2017-05-01T03:30:00","title":"Eastern Conf Semifinals: TBD at Cleveland Cavaliers - Home Game 1 (Date TBA)","created_at":"2017-01-08T00:00:00","type":"nba","performers":[{"url":"https:\/\/seatgeek.com\/cleveland-cavaliers-tickets","short_name":"Cavaliers","type":"nba","home_venue_id":120,"slug":"cleveland-cavaliers","image_attribution":"https:\/\/commons.wikimedia.org\/wiki\/Category:Quicken_Loans_Arena#\/media\/File:Quicken_Loans_Arena_WV_photo.jpg","image_license":"https:\/\/creativecommons.org\/licenses\/by\/2.0\/","score":0.682381,"home_team":true,"divisions":[{"display_name":"Eastern Conference","slug":null,"division_level":1,"display_type":"Conference","short_name":null,"taxonomy_id":1030100},{"display_name":"Eastern - Central","slug":"eastern-central","division_level":2,"display_type":"Division","short_name":"Central","taxonomy_id":1030100}],"stats":{"event_count":18},"has_upcoming_events":true,"colors":{"iconic":"#860038","primary":["#860038","#FDBB30"],"all":["#860038","#FDBB30","#002D62"]},"images":{"huge":"https:\/\/chairnerd.global.ssl.fastly.net\/images\/performers-landscape\/cleveland-cavaliers-f228fd\/2094\/huge.jpg"},"name":"Cleveland Cavaliers","primary":true,"image":"https:\/\/chairnerd.global.ssl.fastly.net\/images\/performers-landscape\/cleveland-cavaliers-f228fd\/2094\/huge.jpg","id":2094,"num_upcoming_events":18,"taxonomies":[{"name":"sports","id":1000000,"parent_id":null},{"name":"basketball","id":1030000,"parent_id":1000000},{"name":"nba","id":1030100,"parent_id":1030000}]}],"datetime_tbd":true,"visible_until_utc":"2017-05-02T04:00:00","date_tbd":true,"score":0.750573,"time_tbd":true,"datetime_utc":"2017-05-01T07:30:00","stats":{"average_price":112.0,"listing_count":1473,"lowest_price":47.0,"lowest_price_good_deals":47.0,"highest_price":12445.0},"announce_date":"2017-01-08T00:00:00","in_hand":{},"is_open":false,"short_title":"E Conf Semis - Home Gm 1: TBD at Cavaliers","links":[],"id":3693387,"venue":{"timezone":"America\/New_York","url":"https:\/\/seatgeek.com\/venues\/quicken-loans-arena\/tickets","display_location":"Cleveland, OH","name_v2":"Quicken Loans Arena","state":"OH","postal_code":"44115","links":[],"slug":"quicken-loans-arena","num_upcoming_events":35,"id":120,"extended_address":"Cleveland, OH 44115","address":"1 Center Court","has_upcoming_events":true,"name":"Quicken Loans Arena","city":"Cleveland","location":{"lat":41.4971,"lon":-81.6884},"country":"US","score":0.739077},"taxonomies":[{"name":"sports","id":1000000,"parent_id":null},{"name":"basketball","id":1030000,"parent_id":1000000},{"name":"nba","id":1030100,"parent_id":1030000}]}

**Comment by josegonzalez** [comment]
NBA Finals games aren't guaranteed to happen, so the date and time is TBD until both teams are decided for the particular games.

**Comment by yehoshuas** [comment]
Hi again,
I noticed that the location in the events is not always matching the address location, for example in event #3761372 the location returned is 40.7128, -74.0059 (New York City Hall), but the address in the venue is "125 E 11th St, New York", I used Google Maps to check the coordinates of the address and got this location 40.731680, -73.989171, notice that this location is also what I get when I look for the venue name (The Studio at Webster Hall) in Google maps.

is the venue location the real location of the event? and if not so, how can I know the event location

here is the API call I used
https://api.seatgeek.com/2/events/3761372?client_id=

and here is the response:
{"created_at":"2017-02-24T00:00:00","title":"Ponicz","short_title":"Ponicz","datetime_tbd":false,"general_admission":true,"type":"concert","datetime_local":"2017-04-29T23:00:00","venue":{"city":"New York","url":"https:\/\/seatgeek.com\/venues\/the-studio-at-webster-hall\/tickets","state":"NY","country":"US","postal_code":"10003","score":0.494263,"has_upcoming_events":true,"slug":"the-studio-at-webster-hall","extended_address":"New York, NY 10003","name":"The Studio at Webster Hall","name_v2":"The Studio at Webster Hall","location":{"lon":-74.0059,"lat":40.7128},"address":"125 E 11th St","display_location":"New York, NY","id":9231,"links":[],"timezone":"America\/New_York","num_upcoming_events":11},"date_tbd":false,"datetime_utc":"2017-04-30T03:00:00","performers":[{"has_upcoming_events":true,"image_license":null,"type":"band","score":0.0,"slug":"ponicz","primary":true,"stats":{"event_count":3},"image_attribution":null,"images":{},"name":"Ponicz","image":null,"id":387503,"taxonomies":[{"name":"concert","parent_id":null,"id":2000000}],"num_upcoming_events":3,"url":"https:\/\/seatgeek.com\/ponicz-tickets","short_name":"Ponicz","colors":null,"divisions":null,"home_venue_id":null}],"stats":{"lowest_price":115.0,"lowest_price_good_deals":null,"listing_count":3,"highest_price":117.0,"average_price":115.0},"score":0.459219,"time_tbd":false,"id":3761372,"taxonomies":[{"name":"concert","parent_id":null,"id":2000000}],"links":[],"visible_until_utc":"2017-04-30T07:00:00","url":"https:\/\/seatgeek.com\/ponicz-tickets\/new-york-new-york-the-studio-at-webster-hall-2017-04-29-11-pm\/concert\/3761372","announce_date":"2017-02-24T00:00:00","in_hand":{},"is_open":false}

**Comment by yehoshuas** [comment]
Another qustion:
I see that there are events with a title that looks like the ticket text (rather than the event itself), for example (notice that the title contains '3-day-pass' as part of the text):
https://seatgeek.com/shaky-knees-music-festival-3-day-pass-with-the-xx-lcd-soundsystem-phoenix-cage-the-elephant-and-more-tickets/atlanta-georgia-centennial-olympic-park-2017-05-12-3-30-am/music-festival/3426402

**Comment by josegonzalez** [comment]
A few things:

- While we strive for accuracy, sometimes our geolocation data gives us slightly incorrect values. I'll open an issue internally to fix the Webster Hall location, as well as look to see if we can source that data from multiple places/reconcile them better.
- Some events have multi-day passes - festivals usually - and we split those off into different events so as to less confuse our users.

**Comment by yehoshuas** [comment]
can you give an estimate on what is the percentage of places with an inaccurate location.

also is there a way that I can estimate that a location might be wrong (for example if the extended_address
does not contain the street name?)
