### ISSUE TITLE
Events API for sports only

### ISSUE THREAD

**Issue by dandemel** [seatgeek/api-support#45]
Is there a way to filter events by type? I am trying to query sports events but most of the results am getting using the generic events API are music related events

**Comment by josegonzalez** [comment]
You can filter by taxonomies using the `taxonomies.id=1000000` querystring argument. Taxonomies are a tree structure, so any MLB event (`1010100`) is also a Baseball event (`1010000`), and any Baseball event is also a Sports event (`1000000`).

Taxonomies can be retrieved via the [taxonomies](https://api.seatgeek.com/2/taxonomies) endpoint.
