### ISSUE TITLE
lowest price is not accurate

### ISSUE THREAD

**Issue by mattr9** [seatgeek/api-support#48]
Using the events API and checking the stats it shows the lowest price is $489
https://api.seatgeek.com/2/events/3906212

same with the web view which i assume uses the same stat
![screen shot 2017-07-29 at 6 52 16 pm](https://user-images.githubusercontent.com/30559950/28749249-1b8bd0fa-748f-11e7-9416-4e43080201ba.png)

upon opening the event the lowest price is actually $110. this was checked at 6:54pm eastern on july 29, 2017. the API and even parts of your website are not showing an accurate lowest price.

![screen shot 2017-07-29 at 6 54 03 pm](https://user-images.githubusercontent.com/30559950/28749254-52afb268-748f-11e7-8d9a-bd748a5e76cc.png)

**Comment by josegonzalez** [comment]
This data is updated in semi-realtime, and if the data refreshes in between when we would normally cache it, we'll pull the updated data soon. It is otherwise provided under a "best effort" availability.

Hope that clarifies things.
