### ISSUE TITLE
Request data from past events

### ISSUE THREAD

**Issue by jcusick13** [seatgeek/api-support#49]
I just wanted to follow up on issue #20 - regarding querying past events. Has this been implemented or are there plans to include this in the future? If it isn't possible via the API, is there some other method to request historical event price data from Seat Geek? I'm trying to obtain data for a personal, non-commercial project.

Thanks!

**Comment by josegonzalez** [comment]
Our api does not currently expose past events externally, though this is something we're still trying to figure out how to do properly. Rest assured, I'll update this and all other past events issues once this is released.

**Comment by pkmistry24** [comment]
Any update on this matter @josegonzalez ? Also why in the API documentation does it include the date-time arguments for pulling past events, if this option isn't currently available. Thanks.

**Comment by josegonzalez** [comment]
@pkmistry24 at this time, we do not publicly support past events. Datetime filtering is enabled because you might want a range of time in the future.

**Comment by vr16x** [comment]
@josegonzalez if we have an event id of past event stored somewhere, can we fetch the event details for that specific past event ?

**Comment by josegonzalez** [comment]
@venkatesh16031999  at this time, we do not publicly support past events. Datetime filtering is enabled because you might want a range of time in the future.
