### ISSUE TITLE
Can the API be used on an alternate site that sells tickets?

### ISSUE THREAD

**Issue by cosmointeractive** [seatgeek/api-support#5]
I was wondering what are the possibilities of using SeatGeeks's maps on a site that I am building. Where do I access it? Are there any fees to using it? What are my limitations?

**Comment by erwaller** [comment]
We currently don't allow our maps to be used by third parties. Sorry about that.

You can use the API to help sell tickets you own, but not to display tickets on behalf of other ticket sellers. Check out the "Ticket listings" section in https://seatgeek.com/api-terms for more detail.
