### ISSUE TITLE
Cancelled events

### ISSUE THREAD

**Issue by robertkern** [seatgeek/api-support#52]
Hi there,

Via the API, how do we know which events have been cancelled? The Seatgeek website seems to know that an event has been cancelled/expired, but unsure how to detect this via the API data.

Thanks!

**Comment by robertkern** [comment]
Nobody?

**Comment by acslater00** [comment]
Hi Robert, we don't include cancelled events in our API response - you can use the absence of a particular event id (eg a 404 response from `/events/<event-id>` as an indication that the event has either been cancelled in real life or removed from seatgeek.

**Comment by aasingla** [comment]
Not getting the cancelled event in the next API feed is not helpful enough since it is a difficult comparison to make. It would be excellent if you could send across the cancelled events with a property that signifies that the event is cancelled.
