### ISSUE TITLE
Partnership, Sales and Monetization through api?

### ISSUE THREAD

**Issue by n8stowell82** [seatgeek/api-support#54]
Hello,  this is not an issue per se but more of a question for clarification.  I am reading through your docs, and cannot understand how the monetization system works.  Maybe this is due to my preconceived idea of how the api _should_ work vs how it *actually* works.  I am building a mobile app that I am planning on consuming the list of events from your api to display to my customers.  It seems a natural extension to allow the user to be able to purchase tickets directly from within the application.  However, I am not seeing any _clear_ documentation on this part one way or the other.  I cannot tell how I am supposed to take an interested customer and move them to a paying customer? Am I missing some critical piece of documentation? I have seen the little blip about adding `aid` to the end of a request, but that is about all I can find about how a "partner" works. 

Thank you for your time

**Comment by Russpd** [comment]
@n8stowell82 thanks for your question and interest! We recently rolled out a product called SeatGeek Open (https://enterprise.seatgeek.com/features/seatgeek-open) that allows this capability but only for teams who SeatGeek is the primary ticketing provider for (currently it's scoped to MLS teams like Sporting KC). If you are interested in learning more, please reach out to us here: https://enterprise.seatgeek.com/contact and we'll get you set up

**Comment by josegonzalez** [comment]
Closing as I believe this was resolved :)
