### ISSUE TITLE
maximum per page value allowed by API

### ISSUE THREAD

**Issue by DSIQBJackman** [seatgeek/api-support#58]
I could not find the answers to the following questions in the documentation...

What is the maximum "per page" value allowed by the API? 
What is the recommended "per page" value we should use?
Do you throttle a client if they pull too much data? If so what is your throttling thresholds so we can remain a good client. 

Here is our Issue: (This was working yesterday)
When we make the following call
https://api.seatgeek.com/2/events?per_page=1000&page=1&sort=datetime_utc.asc&client_id=xxxxxxxxxxx&venue.country=US&datetime_utc.lt=2018-08-26

We get back a status code of 200 but the json is the following:
{"meta":{"page":1,"geolocation":null,"total":0,"per_page":1000,"took":0},"events":[]}

If we change the call to only return 100 records per page we get back a full json with 100 Event details. 

The per page value of 1000 had been working for us for months (we pull 100K events once a day), now today(Feb 27th 2017) pulling 1000 does not work (see above).  It appears to be related to the size of the data for if I reduce the per page to 305 it works for some pages but not others. 

Any help or guidance on what is occurring would be helpful for us.

Thank you

**Comment by zackkitzmiller** [comment]
@DSIQBJackman I think you caught a bug on our end. Can you check again to see if this is resolved?

**Comment by DSIQBJackman** [comment]
Your assumption of a bug appears to be correct. When I request 1000 events per page, the JSON is being populated correctly again. 

Thank you for your help
