### ISSUE TITLE
I want to create a simple affiliation URL

### ISSUE THREAD

**Issue by ashlasbl** [seatgeek/api-support#61]
Hi,
I would like to know how i can send you affiliated traffic without using the API.
Is there anything that i can add to your link to track my referrals?
Example : https://seatgeek.com/venues/at-t-stadium/tickets . Can i just add my partner ID like this https://seatgeek.com/venues/at-t-stadium/tickets?aid=12345 . Is that enough to track my referrals?
kind Regards,
Ashl

**Comment by zackkitzmiller** [comment]
Yup that’s all you need to do. You’ll notice the aid removed from the url but it will be saved in the users cookie.

**Comment by ashlasbl** [comment]
THANK YOU VERY MUCH :) :) 👍
