### ISSUE TITLE
Query with keywords?

### ISSUE THREAD

**Issue by Muirski2992** [seatgeek/api-support#62]
I'm coming from a system which uses the ticketmaster api and I'm attempting to switch over to using seatgeek.  With ticketmaster I am able to query for things like "toronto" "leafs" "toronto leafs" "toronto maple leafs" etc.  Based on the examples and based on my own initial attempts, I'm under the impression that I can only query seat geek with using "toronto-maple-leafs"?? Anything else just returns a mostly empty response.

**Comment by vaibhavkaul** [comment]
@Muirski2992 what is the response you get when you try

```shell
curl 'https://api.seatgeek.com/2/performers?q=toronto&client_id=<your_client_id>'
```

**Comment by Muirski2992** [comment]
q works perfectly. Thanks very much. I didn't see that in the documentation. i'd been using performers.slug=<query>
