### ISSUE TITLE
Cannot fetch more than 10,000 events using pagination

### ISSUE THREAD

**Issue by DSIQBJackman** [seatgeek/api-support#63]
I invoke the following URL: 
https://api.seatgeek.com/2/events?per_page=1000&page=1&sort=datetime_utc.asc&client_id=xxxxxxxxxxxxxxx&venue.country=US&datetime_utc.lt=2018-10-07 and I get back 1000 events. 

I call this same URL for page 2-10 and again it works correctly but as soon as I call it for page 11-105 I get back an empty set 
   {"meta":{"page":11,"took":0,"total":0,"geolocation":null,"per_page":1000},"events":[]}
the metadata says I have 105K records
   {"meta":{"total":105132,"per_page":1000,"geolocation":null,"page":1,"took":43},
so I should be able to call the url for 105 pages each with 1000 events.

I changed the URL to pull only 500 events 
https://api.seatgeek.com/2/events?per_page=500&page=1&sort=datetime_utc.asc&client_id=xxxxxxxxxxxxxxx&venue.country=US&datetime_utc.lt=2018-10-07 and I get back 5000 events for pages 1-20 but as soon as I called it for page 21 and up I got back the empty set. 

Can somebody investigate this possible bug and fix it. 
Thank you

**Comment by DSIQBJackman** [comment]
Additional Information: This issue appears to be intermittent. If I run the same queries I just tested with with page number above 10 they are working correctly now. (15 minutes ago they were not working correctly). This is a recurring issue for us in that we first discovered this issue on Friday Apr 6th around 7:00am PST and again on Monday and Tuesday Morning (Apr 9th and 10th) but did not experience this issue on Sat. or Sun (Apr 7th or 8th) All queries were executed around the 7:00am hour (PST).

**Comment by zackkitzmiller** [comment]
We've identified the configuration issue and are rolling out the fix now.

**Comment by zackkitzmiller** [comment]
@DSIQBJackman Can you confirm this is no longer an issue? If so, I'll close this ticket.

**Comment by DSIQBJackman** [comment]
Wow in 30 minutes we have a response and fix. Thank you for the great support. Keep up the good work.

**Comment by zackkitzmiller** [comment]
@DSIQBJackman Thanks!
