### ISSUE TITLE
How To resolve Taxonomies name.

### ISSUE THREAD

**Issue by chukwumaijem** [seatgeek/api-support#64]
Hi, I'm working on a platform that uses event taxonomies for search. However, I can't seem to resolve the type that appears on the events API call to the type I see in the event's script when I visit the URL on the browser.

Take this [event](https://seatgeek.com/festival-of-disruption-sunday-only-with-angel-olsen-jim-james-au-revoir-simone-and-more-tickets/brooklyn-new-york-brooklyn-steel-1-2018-05-20-3-30-am/music-festival/4291161) for example, the type of event is @type: "MusicEvent" and @type: "Event". On the API result, I see type "music-festival" with the taxonomies of "music_festival" and "concert"(not "Event" I just saw in the script tag). On getting to the taxonomies API, "music_festival" resolves to "Music Festival"(not Music Event).

So how did you/how do I map the type in the API result to the type in the script tags?

### Screenshots

- ##### Script Tag

<img width="1273" alt="screen shot 2018-05-20 at 11 24 43 am" src="https://user-images.githubusercontent.com/17248267/40278024-53cb971e-5c21-11e8-8642-8ac47b29c9b8.png">

- ##### Event API Type

<img width="1015" alt="screen shot 2018-05-20 at 11 25 28 am" src="https://user-images.githubusercontent.com/17248267/40278025-5475b0b4-5c21-11e8-8753-f9fd786efdfd.png">

- ##### Taxonomies API

<img width="503" alt="screen shot 2018-05-20 at 11 27 09 am" src="https://user-images.githubusercontent.com/17248267/40278026-54b5454e-5c21-11e8-95c1-e5f6e2be0f28.png">

**Comment by josegonzalez** [comment]
We do not resolve schema.org on our external API, and would prefer that you _not_ screenscrape our seatgeek.com domain.

For your use case, you can ascribe events with an id in it's tree of `2000000` as a MusicEvent. The tree `1000000` is used for sports, and `3000000` is for the arts and other types of events.

I suggest pulling in the taxonomies endpoint and mapping those events to any other schema as appropriate. We're unlikely to expose that data in our api in the near future.

Hope this helps.

**Comment by chukwumaijem** [comment]
Yea, that was helpful.
