### ISSUE TITLE
Score

### ISSUE THREAD

**Issue by jmp1994** [seatgeek/api-support#7]
I'm a college student working on my senior thesis and I'm attempting to analyze the secondary ticket market for festivals in my research. I came across the SeatGeek API and saw the "Score" variable which I'm hoping to implement into my project but have a question about it. 

1. Can you tell me how the estimated sales volume is calculated to create Score? 

Or if not, at least tell if it is partially based on historical sales for an event/artist or is it only reflecting expected future sales based on current demand?

So for example, an artists' score would be very high while they're on tour, but then drop down again once they aren't playing any shows.

Thank you for your help,
Julian Perez

**Comment by steverit** [comment]
Hi Julian,

The variable is based off of historic data, it makes no effort to guess future sales. 

> So for example, an artists' score would be very high while they're on tour, but then drop down again once they aren't playing any shows.

The score would not drop. The highest score events have the highest scores all year long.

**Comment by jmp1994** [comment]
Hi Steve,

Thank you so much for this, I really appreciate it.

Have a great weekend,
Julian
