### ISSUE TITLE
issue in getting ticket price list and map for ground.

### ISSUE THREAD

**Issue by jigarkanani** [seatgeek/api-support#70]
I am integrating seatgeek in my ios app. I successfully get event list as my requirement. Now i want to get ticket price list for that event. but i don't get exact solution for that.

My api for get event:- "https://api.seatgeek.com/2/events?client_id=[My Client Id]&taxonomies.name=sports&per_page=20&page=1&sort=datetime_utc.asc"
Now i want to get price list and ground image for any particular event.

**Comment by dallasgutauckis** [comment]
@jigarkanani we do not have a public API or SDK that exposes a list of prices or map data. You can, however, use the `stats` portion of that response to get things like min, avg, and max price for the event(s).
