### ISSUE TITLE
What is the timezone for the events shown by seatgeek

### ISSUE THREAD

**Issue by saishneugi** [seatgeek/api-support#77]
I am trying to fetch events based on the events that I have on ticket evolution. So I pass a request using query parameter and datetime_local. But the events always shows mismatched date and time as compared to ticket evolution. So wanted to know what is the timezone that is used by SeatGeek to show the events

**Comment by josegonzalez** [comment]
The timezones is local to the venue. If you want to compare across services, I suggest looking at datetime_utc and generating a timezones based on the venue location.
