### ISSUE TITLE
Past Events in SeatGeek API

### ISSUE THREAD

**Issue by amseet** [seatgeek/api-support#79]
Greetings,

I'm a Master student and part of my project is obtaining past events (2015 to 2018) for New York City. I was hoping you would allow me access to past events through SeatGeek API. It would help me greatly in my project. Or if you could provide a CSV file for NYC 2015 and 2016 events that would be great too.

Thank you very much for your help.

**Comment by jonmcoe** [comment]
Unfortunately, api.seatgeek.com does not surface past events.

The CSV route may potentially be possible. Depends on what exactly you want, whether it is something we are willing to share, and how much effort it would take to make you such a CSV. Can you be more specific in what you're hoping for?

**Comment by amseet** [comment]
Thank you @jonmcoe for your reply.
I was hoping for all the 2015 events for New York City. 

Basically running this query would be enough:
https://api.seatgeek.com/2/events?
datetime_utc.gte=2015-01-01
&datetime_utc.lt=2016-01-01
&venue.state=NY

Looking for these attributes:
Event ID
Event Name
Date & Time
Event Type (Music, sport, etc)
Address
Venue

If you require any further information or official documents, please email me directly and I would be glad to oblige.
Thank you so much for your help.

**Comment by jonmcoe** [comment]
i have emailed you. good luck!
