### ISSUE TITLE
How Filter a Event list By Type

### ISSUE THREAD

**Issue by shihabvk** [seatgeek/api-support#8]
Hi ,

I have a plan to integrate your API in my App.But i only need sports related Events.How i filter the events API based on event type?I also need to get the team details that participate in the event. is this available.

Help is highly appreciable.

**Comment by dallasgutauckis** [comment]
This specific use case is covered as part of the [platform documentation](http://platform.seatgeek.com) in the Events subsection (look for "taxonomies Argument")
