### ISSUE TITLE
Getting All Sports and Their Associated Teams

### ISSUE THREAD

**Issue by 1993alexey** [seatgeek/api-support#83]
I went through the API docs, but didn't find anything that would allow me to pull a list of all sport names and their associated teams. 

Is there a way to get a similar list to this:
Sports
MLB
NFL
NBA
NHL
MLS
NCAA FB
NCAA BB
etc.

Teams for MLB
Arizona Diamondbacks
Atlanta Braves
Baltmore Orioles
Boston Red Sox
Chicago Cubs
Chicago White Sox
etc.

**Comment by byrnehollander** [comment]
👋 Hey Alex,

Something like this might work:

`https://api.seatgeek.com/2/performers?taxonomies.name=mlb&per_page=100&client_id={{CLIENT_ID}}`

<details>
  <summary>Full List of Taxonomies</summary>
  <table>
    <tr>
        <td>taxonomy name</td>
        <td>taxonomy ID</td>
    </tr>
    <tr>
        <td>sports</td>
        <td>1000000</td>
    </tr>
    <tr>
        <td>baseball</td>
        <td>1010000</td>
    </tr>
    <tr>
        <td>mlb</td>
        <td>1010100</td>
    </tr>
    <tr>
        <td>ncaa_baseball</td>
        <td>1010200</td>
    </tr>
    <tr>
        <td>minor_league_baseball</td>
        <td>1010300</td>
    </tr>
    <tr>
        <td>football</td>
        <td>1020000</td>
    </tr>
    <tr>
        <td>nfl</td>
        <td>1020100</td>
    </tr>
    <tr>
        <td>ncaa_football</td>
        <td>1020200</td>
    </tr>
    <tr>
        <td>basketball</td>
        <td>1030000</td>
    </tr>
    <tr>
        <td>nba</td>
        <td>1030100</td>
    </tr>
    <tr>
        <td>ncaa_basketball</td>
        <td>1030200</td>
    </tr>
    <tr>
        <td>ncaa_womens_basketball</td>
        <td>1030300</td>
    </tr>
    <tr>
        <td>wnba</td>
        <td>1030400</td>
    </tr>
    <tr>
        <td>nba_dleague</td>
        <td>1030500</td>
    </tr>
    <tr>
        <td>hockey</td>
        <td>1040000</td>
    </tr>
    <tr>
        <td>nhl</td>
        <td>1040100</td>
    </tr>
    <tr>
        <td>ncaa_hockey</td>
        <td>1040200</td>
    </tr>
    <tr>
        <td>minor_league_hockey</td>
        <td>1040300</td>
    </tr>
    <tr>
        <td>soccer</td>
        <td>1050000</td>
    </tr>
    <tr>
        <td>mls</td>
        <td>1050100</td>
    </tr>
    <tr>
        <td>ncaa_soccer</td>
        <td>1050200</td>
    </tr>
    <tr>
        <td>european_soccer</td>
        <td>1050300</td>
    </tr>
    <tr>
        <td>international_soccer</td>
        <td>1050400</td>
    </tr>
    <tr>
        <td>world_cup</td>
        <td>1050401</td>
    </tr>
    <tr>
        <td>us_minor_league_soccer</td>
        <td>1050500</td>
    </tr>
    <tr>
        <td>auto_racing</td>
        <td>1060000</td>
    </tr>
    <tr>
        <td>nascar</td>
        <td>1060100</td>
    </tr>
    <tr>
        <td>nascar_sprintcup</td>
        <td>1060101</td>
    </tr>
    <tr>
        <td>nascar_nationwide</td>
        <td>1060102</td>
    </tr>
    <tr>
        <td>indycar</td>
        <td>1060200</td>
    </tr>
    <tr>
        <td>f1</td>
        <td>1060300</td>
    </tr>
    <tr>
        <td>monster_truck</td>
        <td>1060400</td>
    </tr>
    <tr>
        <td>motocross</td>
        <td>1060500</td>
    </tr>
    <tr>
        <td>golf</td>
        <td>1070000</td>
    </tr>
    <tr>
        <td>pga</td>
        <td>1070100</td>
    </tr>
    <tr>
        <td>lpga</td>
        <td>1070200</td>
    </tr>
    <tr>
        <td>fighting</td>
        <td>1080000</td>
    </tr>
    <tr>
        <td>boxing</td>
        <td>1080100</td>
    </tr>
    <tr>
        <td>mma</td>
        <td>1080200</td>
    </tr>
    <tr>
        <td>wrestling</td>
        <td>1080300</td>
    </tr>
    <tr>
        <td>wwe</td>
        <td>1080301</td>
    </tr>
    <tr>
        <td>tennis</td>
        <td>1090000</td>
    </tr>
    <tr>
        <td>animal_sports</td>
        <td>1100000</td>
    </tr>
    <tr>
        <td>horse_racing</td>
        <td>1100100</td>
    </tr>
    <tr>
        <td>rodeo</td>
        <td>1100200</td>
    </tr>
    <tr>
        <td>extreme_sports</td>
        <td>1110000</td>
    </tr>
    <tr>
        <td>olympic_sports</td>
        <td>1120000</td>
    </tr>
    <tr>
        <td>band</td>
        <td>2000000</td>
    </tr>
    <tr>
        <td>band</td>
        <td>2000001</td>
    </tr>
    <tr>
        <td>music_festival</td>
        <td>2010000</td>
    </tr>
    <tr>
        <td>theater</td>
        <td>3000000</td>
    </tr>
    <tr>
        <td>theater_classical</td>
        <td>3010000</td>
    </tr>
    <tr>
        <td>theater_classical_opera</td>
        <td>3010100</td>
    </tr>
    <tr>
        <td>theater_classical_vocal</td>
        <td>3010200</td>
    </tr>
    <tr>
        <td>theater_classical_orchestral_instrumental</td>
        <td>3010300</td>
    </tr>
    <tr>
        <td>cirque_du_soleil</td>
        <td>3020000</td>
    </tr>
    <tr>
        <td>theater_broadway_national_tours</td>
        <td>3030000</td>
    </tr>
    <tr>
        <td>theater_comedy</td>
        <td>3040000</td>
    </tr>
    <tr>
        <td>theater_family</td>
        <td>3050000</td>
    </tr>
    <tr>
        <td>theater_dance_performance_tour</td>
        <td>3060000</td>
    </tr>
    <tr>
        <td>film</td>
        <td>3070000</td>
    </tr>
    <tr>
        <td>literary</td>
        <td>3080000</td>
    </tr>
    <tr>
        <td>circus</td>
        <td>3090000</td>
    </tr>
</table>
</details>

**Comment by 1993alexey** [comment]
@byrnehollander, thanks, that works for obtaining a list of sports. Do you know how I would pull a list of teams associated with a sport? 

For example, I need to obtain a list of teams for MLB. It seems like at this point there is nothing on SeatGeek that provides that functionality.

**Comment by sddamico** [comment]
Hey @1993alexey, the `/performers` API that Byrne suggested at the top of the post does exactly what you're asking. Just drop your client id in there and give it a spin.

**Comment by byrnehollander** [comment]
@1993alexey You can use this `https://api.seatgeek.com/2/performers?taxonomies.name=mlb&per_page=100&client_id={{CLIENT_ID}}` to get a list of MLB teams – the catch is that there are some "performers" returned in the `performers` array that aren't real performers (like `World Series`). 

So, you'd have to iterate through the array of performer objects... and for MLB at least, it's a team when `divisions` is not `null`

**Comment by 1993alexey** [comment]
@sddamico, you're right, my bad. That is exactly what I was looking for. Since API docs don't have a definition of performers, I thought it was related to concerts or circus. 

Do you know where I could obtain team icons? For example, I want to get an icon for MLB Minnesota Twins team, but the performers API doesn't contain it. 

Thanks again for your help, I appreciate your time.

**Comment by sddamico** [comment]
SeatGeek does not have the rights to use team iconography and logos, you'll have to find those elsewhere, sorry.
