### ISSUE TITLE
[Platform > Manage Apps] Application name and styling issues

### ISSUE THREAD

**Issue by stephenyeargin** [seatgeek/api-support#9]
Wanted to bring a few issues to your attention.
- No matter what you provide for an application name when registering, it will call it "Unnamed App" on the next page. You can then go in and update the name.
- The initial form for registering the application indicates the redirect URL is deprecated, but the edit form does not.
- The table listing the application looks like it is missing CSS styles, or at least could use a bit more padding for cell content; potentially fixed by dropping the empty 'Redirect URL' column entirely.

![](http://dropbox.stephenyeargin.com/Rr426.png)

**Comment by josegonzalez** [comment]
Good catch! I'll open these in our internal issue tracker/try and fix them myself if I have some time later today.

**Comment by josegonzalez** [comment]
Seems like the issues were fixed by another dev :)

![http://cl.ly/0x402X0F0B46](http://cl.ly/0x402X0F0B46/Image%202016-05-12%20at%206.22.19%20PM.png)

(Ignore the unnamed app in this, its from screwing around with the system locally).
