### ISSUE TITLE
Filter event by Genre?

### ISSUE THREAD

**Issue by msu11y** [seatgeek/api-support#95]
Hello,

Is it possible to pass a genre into the Events endpoint? 

I see you can filter by performer, venue, date, query, ID, and taxonomy. I tried passing in the genre ID, but that didn't seem to work. I'm not sure if in the natural language section of query, I can pass in something like "rock genre"...?

Thanks!

**Comment by msu11y** [comment]
Hello, just checking in :)

**Comment by chrisvoll** [comment]
Hey @msu11y!

It's possible to filter events by genre using the `genres[primary].slug` key:

https://api.seatgeek.com/2/events?genres[primary].slug=country&client_id=YOUR_CLIENT_ID

You can also get the list of available genres here:

https://api.seatgeek.com/2/genres?per_page=30&client_id=YOUR_CLIENT_ID

I'll open a ticket internally to ensure that this is added to the API documentation.

**Comment by msu11y** [comment]
Hi @chrisvoll, thank you for that! I see that it registers, but it's not accurate. For example, I passed in the Jazz genre, and it is returning performers (via events endpoint) that do not have Jazz as a genre. 

Thoughts?

**Comment by chardigio** [comment]
Would you mind providing an example of an incorrect response? Perhaps only one of the event's performers have the jazz genre? Either way our team is happy to look into it and see what's going on.

**Comment by msu11y** [comment]
Sure @cd17822 ! So if you hit the Performer endpoint for Jonas Brothers, they have 2 genres attached to them: Rock and Pop. If you hit the Events endpoint within 4 miles of 92110 with " genres[primary].slug=jazz " as a parameter, you will see Jonas Brothers listed (who are definitely not Jazz). 

You should see other example who are not Jazz also, like...Sum 41 and Tyler the Creator.

This happens for other genres also (not just Jazz).

Thanks for looking into this!!

**Comment by chardigio** [comment]
@msu11y I'm trying to reproduce your issue with this

https://api.seatgeek.com/2/events?client_id=<redacted>&genres[primary].slug=jazz&lat=32.7657&lon=-117.2

and I'm not seeing any of the performers you mentioned. Mind posting the query you're trying to make?

**Comment by msu11y** [comment]
Hey @cd17822, I found my issue--the genre parameter was being chopped off the URL at one point in our code...

While, it looks more accurate now, it doesn't seem 100% still...

When I use the below URL, ' tyler, the creator ' is in the result set. But his primary genre (id=13719) is Rap (not Rock). Can you take a look, if you wouldn't mind?

https://api.seatgeek.com/2/events?client_id=******************************&geoip=92110&range=4mi&per_page=5000&datetime_local.lt=2019-11-08&listing_count.gt=0&genres[primary].slug=Rock

Thank You!!!

**Comment by msu11y** [comment]
@cd17822 @chrisvoll Have you had a chance to review my above issue? 

Thank you for taking the time to investigate this, it means a lot!

**Comment by msu11y** [comment]
Any update? Our team is kind of stuck until we know this is working accurately... @chrisvoll  @cd17822

**Comment by msu11y** [comment]
Same situation if you pass in Rap genre for 10 miles of zip code = 90012. one of the results is Enrique Iglesias (not rap). His 2 genre tags are Pop and Latin....Can we please get this looked at? It's been a month since I first brought this issue to surface. This is very frustrating. @chrisvoll @cd17822

**Comment by msu11y** [comment]
Seatgeek obviously isnt' paying attention. But I figured it out to anyone else out there who ran into this. It seems to be because the performer is apart of a festival / concert where the main artist's genre is different.
